import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:nutri_scan/data/api/response_model.dart';

import 'get_model.dart';

class DioClient {
  DioClient._internal();

  static final DioClient instance = DioClient._internal();

  late final _dio = Dio();

  Future<Autogenerated?> getRecommendations(String content) async {
    _dio.options.headers['Content-Type'] = 'application/json';

    final data = {
      "content": content.replaceAll('\n', ''),
    };
    debugPrint('Api Request: $data');

    try {
      final response = await _dio.post(
        'http://10.1.132.144:3000/api/recommend',
        data: data,
        options: Options(
          sendTimeout: Duration(minutes: 10),
          receiveTimeout: Duration(minutes: 10),
        ),
      );
      debugPrint(response.toString());
      return Autogenerated.fromJson(response.data);
    } catch (e) {
      debugPrint('Error: $e');
    }
    return null;
  }

  Future<AutogeneratedGet?> getHttp() async {
    try {
      final response = await _dio.get('http://10.1.212.26:3080/chat');
      debugPrint(response.toString());

      return AutogeneratedGet.fromJson(response.data);
    } catch (e) {
      debugPrint('Error: $e');
    }
    return null;
  }
}
