class AutogeneratedGet {
  String? ingredient;
  String? summary;

  AutogeneratedGet({this.ingredient, this.summary});

  AutogeneratedGet.fromJson(Map<String, dynamic> json) {
    ingredient = json['Ingredient'];
    summary = json['Summary'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Ingredient'] = this.ingredient;
    data['Summary'] = this.summary;
    return data;
  }
}
