class Autogenerated {
  ResponseData? response;

  Autogenerated({this.response});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    response = json['response'] != null
        ? new ResponseData.fromJson(json['response'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.response != null) {
      data['response'] = this.response!.toJson();
    }
    return data;
  }
}

class ResponseData {
  String? summary;
  String? unhealthy;
  String? verdict;

  ResponseData({this.summary, this.unhealthy, this.verdict});

  ResponseData.fromJson(Map<String, dynamic> json) {
    summary = json['Summary'];
    unhealthy = json['Unhealthy'];
    verdict = json['Verdict'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Summary'] = this.summary;
    data['Unhealthy'] = this.unhealthy;
    data['Verdict'] = this.verdict;
    return data;
  }
}
